apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps-of-apps
  namespace: argocd
spec:
  description: App of Apps project with multi-environment support

  sourceRepos:
  - '*'

  destinations:
  # Allow Argo CD to create and manage Applications
  - namespace: argocd
    server: https://kubernetes.default.svc

  # Allow workload deployments
  - namespace: dev
    server: https://kubernetes.default.svc
  - namespace: staging
    server: https://kubernetes.default.svc
  - namespace: prod
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

